### PR TITLE
feat: add GPLv3 license

### LINKED ISSUE #2: Feature request: introducing a license to this project
👋 Hello, @soundxyz! 

Long-time subscriber here, first-time public-issue opener. 😉 

Thank you for open-sourcing these contracts.

So... I'm wondering if you have any plans to [choose and implement a license](https://choosealicense.com/) for this project? As I understand it, there is currently [no license](https://choosealicense.com/no-permission/). It follows then, that this work is under exclusive copyright by default. The reason I ask is because I'm interested in contributing to the project! 🙇‍♂️

Based on the [ArtistCreatorProxy contract](https://etherscan.io/address/0x78e3adc0e811e4f93bd9f1f9389b923c9a3355c2#code) on mainnet, I believe the most appropriate license for this project is MIT, or perhaps GPLv3? 💭

In any case, I cut a PR for it here to get the ball rolling: https://github.com/soundxyz/protocol-public/pull/1

### PR DESCRIPTION
**Pull request by almndbtr**
## Summary

Closes #2

This adds the GPLv3 license to the root of the repo.

### CODE REVIEW

**Comment by gigamesh** [comment]
@almndbtr thanks for this! we're using the GPL3 license in our contracts though. could you replace with that?

**Comment by almndbtr** [comment]
@gigamesh - Happy to oblige! I'll replace it and loop back once it's pushed up. 👍

**Comment by almndbtr** [comment]
@gigamesh - Done ✅

I'm not sure if there's anything else that needs to change within the license, but let me know if there's anything else I can push before getting this merged in. 😸

**Review by gigamesh — APPROVED** [review]

**Review by PabloSzx — COMMENTED** [review]
btw, this LICENSE was not added to the packages, and because of that, the npm packages are still set as unlicensed

**Comment by almndbtr** [comment]
Hi! I see what you mean - would cutting a new PR introducing the same license per package be enough to resolve that point? Let me know, and I can open an issue to track and a PR to target that fix. ✌🏽

**Comment by almndbtr** [comment]
Also one more thing, for my understanding: which packages in particular need the license? That pointer would help me shape the PR to come. Thanks in advance! 🙏🏾

**Comment by PabloSzx** [comment]
Thank you for your help, the PR https://github.com/soundxyz/protocol-public/pull/10 already fixed it, it was just updating the package.json of common and protocol, and copying the license file to the dist folders 👍

**Pull request merged**
